---

- name: supervisor templates
  template: >
    src={{ item.type }}/supervisor.conf.j2
    dest=/etc/supervisor/conf.d/{{ ((item.project ~ '_') if item.project is defined) ~ item.name }}.conf
  when: elao_services|length > 0
  with_items: elao_services
  notify:
    - supervisor restart
  sudo: yes
